# Generated by Django 4.2.2 on 2023-06-28 13:02

import django.core.validators
from django.db import migrations, models
import petstagram.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), petstagram.common.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), petstagram.common.validators.validate_only_letters]),
        ),
    ]
